version: '3.6'

services:
  postgres:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    hostname: "postgres"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./dumps/postgresql:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
  tor:
    image: chriswayg/tor-server
    restart: always
    ports:
      - '9050:9050'
      - '9051:9051'
      - '9052:9052'
      - '9053:9053'
      - '9054:9054'
      - '9055:9055'
      - '9056:9056'
      - '9057:9057'
      - '9058:9058'
      - '9059:9059'
      - '9060:9060'
      - '9061:9061'
      - '9062:9062'
      - '9151:9151'
    volumes:
      - ./tor-data/:/var/lib/tor/
      - ./torrc:/etc/tor/torrc
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    volumes:
      - ./temp:/app/saver/temp
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "10"