version: '3.6'

services:
  postgres:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    hostname: "postgres"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./dumps/postgresql:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
