"""Added messages table

Revision ID: 3a0b4b2937a8
Revises: 4d8c9fa1ebf1
Create Date: 2023-12-05 13:03:11.322478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0b4b2937a8'
down_revision: Union[str, None] = '4d8c9fa1ebf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_json')
    # ### end Alembic commands ###
